version: '3.1'

services:
  ubuntu:
    build: ./ubuntu
    stdin_open: true
    image: morgushkinalisa/examdocker-site:latest 
  
  site:
    build: ./nginx
    ports:
      - 8080:80
    image: morgushkinalisa/examdocker-site:latest 